### ISSUE TITLE
The experiment details in the 3.2 section

### ISSUE THREAD

**Issue by unknowed-ER** [WilliamsToTo/CGDIALOG#1]
Thank you for your excellent work. In the experiment summarized in 3.2 in the paper, when the model ppl index is calculated, should the entire dialogue history input by the model replace the dialogue history of pad or drop? I sincerely look forward to your answers and open source related code.
Best wishes!

**Comment by WilliamsToTo** [comment]
Thank you for taking an interest in our work. 

> should the entire dialogue history input by the model replace the dialogue history of pad or drop?

We feed the entire dialogue history as input. If the length of input is longer than model's max_length, we truncate the input from the left. We conduct this experiment based on the work of [Do Neural Dialog Systems Use the Conversation History Effectively? An Empirical Study](https://aclanthology.org/P19-1004.pdf).

**Comment by unknowed-ER** [comment]
Thanks for your reply.
